apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |

    - "groups":
    - "system:nodes"
    - "system:bootstrappers"
    "rolearn": "arn:aws:iam::541517706354:role/cfi-ci-eks-workers-role"
    "username": "system:node:{{EC2PrivateDNSName}}"
  - "groups":
    - "system:masters"
    - "system:bootstrappers"
    "rolearn": "arn:aws:iam::541517706354:role/tf-ci-harness-role"
    "username": "harness"

  mapUsers: |

    - "groups":
      - "system:masters"
      "userarn": "arn:aws:iam::541517706354:user/jeremy.malara@castingnetworks.com"
      "username": "jeremy_malara"
